### ISSUE TITLE
Upgrade Pom.xml files to have profiles

### ISSUE THREAD

**Issue by Birdasaur** [Birdasaur/LitFX#11]
The 0.0.4 release has the pom.xml setup to require a GPG passphrase. So if you try to compile it as is it will require the phrase and you will be screwed. 
Need update the pom.xml files so there are profiles such that you only need to enter the phrase when you are attempting to release the artifacts, and thus need to sign them.  (I feel like I spend more time writing XML then Java here...)

**Comment by Birdasaur** [comment]
Being addressed in https://github.com/Birdasaur/LitFX/tree/LitFX-0.0.4-Fixes

**Comment by Birdasaur** [comment]
Pushed changes to branch which include updates to the pom.xml files to support a release profile. By default (default profile) mvn clean install will skip javadoc, source and GPG signing of artifacts. New "release-sign-artifacts" profile will perform these three steps after compilation.
Added NetBeans IDE configurations for this new profile along with a custom Action to do release AND deploy.
Maven CLI is :  mvn -DperformRelease=true clean deploy.

**Comment by carldea** [comment]
I tested the default build using 
`$ mvn clean install`

The build was successful.
Using AzulFX 14.0.2 on Amazon Linux.
