### ISSUE TITLE
CubeViewer demo

### ISSUE THREAD

**Issue by oulfr** [Birdasaur/LitFX#30]
@Birdasaur : hi birdasaur i have searched for the code of the attached exemple and i dont found it ? can you please help[
![tumblr_mv35ur6DYb1swtz6mo1_1280](https://user-images.githubusercontent.com/35069360/98236892-56e57100-1f64-11eb-8f38-0fb790d9bc99.png)
](url)

**Comment by Birdasaur** [comment]
The CubeViewer base code is not part of LitFX, it is part of FXyz3D... https://github.com/FXyz/FXyz
Look in the following package:
https://github.com/FXyz/FXyz/tree/master/FXyz-Core/src/main/java/org/fxyz3d/scene

The original CubeViewer class is there. You may prefer to use CubeWorld which is a more parameterized version.

Have fun.
